package zju.xyb.trade.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zju.xyb.trade.dao.entity.TradeOrder;
import zju.xyb.trade.dao.entity.TradeOrderExample;

public interface TradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    long countByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insert(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insertSelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    List<TradeOrder> selectByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    TradeOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExample(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKeySelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_order
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKey(TradeOrder record);
}