package zju.xyb.trade.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zju.xyb.trade.dao.entity.TradeCoupon;
import zju.xyb.trade.dao.entity.TradeCouponExample;

public interface TradeCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    long countByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insert(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insertSelective(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    List<TradeCoupon> selectByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    TradeCoupon selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TradeCoupon record, @Param("example") TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExample(@Param("record") TradeCoupon record, @Param("example") TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKeySelective(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_coupon
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKey(TradeCoupon record);
}