package zju.xyb.trade.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zju.xyb.trade.dao.entity.TradeUser;
import zju.xyb.trade.dao.entity.TradeUserExample;

public interface TradeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    long countByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insert(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insertSelective(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    List<TradeUser> selectByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    TradeUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TradeUser record, @Param("example") TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExample(@Param("record") TradeUser record, @Param("example") TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKeySelective(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_user
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKey(TradeUser record);
}