package zju.xyb.trade.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zju.xyb.trade.dao.entity.TradePay;
import zju.xyb.trade.dao.entity.TradePayExample;

public interface TradePayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    long countByExample(TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByExample(TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insert(TradePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insertSelective(TradePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    List<TradePay> selectByExample(TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    TradePay selectByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TradePay record, @Param("example") TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExample(@Param("record") TradePay record, @Param("example") TradePayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKeySelective(TradePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_pay
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKey(TradePay record);
}