package zju.xyb.trade.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zju.xyb.trade.dao.entity.TradeGoods;
import zju.xyb.trade.dao.entity.TradeGoodsExample;

public interface TradeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    long countByExample(TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByExample(TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int deleteByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insert(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int insertSelective(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    List<TradeGoods> selectByExample(TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    TradeGoods selectByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") TradeGoods record, @Param("example") TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByExample(@Param("record") TradeGoods record, @Param("example") TradeGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKeySelective(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade..trade_goods
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    int updateByPrimaryKey(TradeGoods record);
}