package zju.xyb.trade.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_coupon.coupon_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_coupon.coupon_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_coupon.user_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_coupon.is_used
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_coupon.used_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Date usedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_coupon.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_coupon.coupon_id
     *
     * @return the value of trade..trade_coupon.coupon_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_coupon.coupon_id
     *
     * @param couponId the value for trade..trade_coupon.coupon_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId == null ? null : couponId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_coupon.coupon_price
     *
     * @return the value of trade..trade_coupon.coupon_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_coupon.coupon_price
     *
     * @param couponPrice the value for trade..trade_coupon.coupon_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_coupon.user_id
     *
     * @return the value of trade..trade_coupon.user_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_coupon.user_id
     *
     * @param userId the value for trade..trade_coupon.user_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_coupon.is_used
     *
     * @return the value of trade..trade_coupon.is_used
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_coupon.is_used
     *
     * @param isUsed the value for trade..trade_coupon.is_used
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setIsUsed(String isUsed) {
        this.isUsed = isUsed == null ? null : isUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_coupon.used_time
     *
     * @return the value of trade..trade_coupon.used_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_coupon.used_time
     *
     * @param usedTime the value for trade..trade_coupon.used_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_coupon.order_id
     *
     * @return the value of trade..trade_coupon.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_coupon.order_id
     *
     * @param orderId the value for trade..trade_coupon.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}