package zju.xyb.trade.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_goods.goods_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_goods.goods_name
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_goods.goods_store
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Integer goodsStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_goods.goods_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_goods.add_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_goods.goods_id
     *
     * @return the value of trade..trade_goods.goods_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_goods.goods_id
     *
     * @param goodsId the value for trade..trade_goods.goods_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_goods.goods_name
     *
     * @return the value of trade..trade_goods.goods_name
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_goods.goods_name
     *
     * @param goodsName the value for trade..trade_goods.goods_name
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_goods.goods_store
     *
     * @return the value of trade..trade_goods.goods_store
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Integer getGoodsStore() {
        return goodsStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_goods.goods_store
     *
     * @param goodsStore the value for trade..trade_goods.goods_store
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsStore(Integer goodsStore) {
        this.goodsStore = goodsStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_goods.goods_price
     *
     * @return the value of trade..trade_goods.goods_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_goods.goods_price
     *
     * @param goodsPrice the value for trade..trade_goods.goods_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_goods.add_time
     *
     * @return the value of trade..trade_goods.add_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_goods.add_time
     *
     * @param addTime the value for trade..trade_goods.add_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}