package zju.xyb.trade.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.user_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.order_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.pay_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.shipping_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String shippingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.address
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.consignee
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.goods_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.goods_num
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Integer goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.goods_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.goods_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal goodsAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.shipping_fee
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal shippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.order_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.coupon_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.coupon_paid
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal couponPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.pay_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.money_paid
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal moneyPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.add_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.confirm_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Date confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_order.pay_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Date payTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.order_id
     *
     * @return the value of trade..trade_order.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.order_id
     *
     * @param orderId the value for trade..trade_order.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.user_id
     *
     * @return the value of trade..trade_order.user_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.user_id
     *
     * @param userId the value for trade..trade_order.user_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.order_status
     *
     * @return the value of trade..trade_order.order_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.order_status
     *
     * @param orderStatus the value for trade..trade_order.order_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.pay_status
     *
     * @return the value of trade..trade_order.pay_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.pay_status
     *
     * @param payStatus the value for trade..trade_order.pay_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.shipping_status
     *
     * @return the value of trade..trade_order.shipping_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.shipping_status
     *
     * @param shippingStatus the value for trade..trade_order.shipping_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setShippingStatus(String shippingStatus) {
        this.shippingStatus = shippingStatus == null ? null : shippingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.address
     *
     * @return the value of trade..trade_order.address
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.address
     *
     * @param address the value for trade..trade_order.address
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.consignee
     *
     * @return the value of trade..trade_order.consignee
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.consignee
     *
     * @param consignee the value for trade..trade_order.consignee
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.goods_id
     *
     * @return the value of trade..trade_order.goods_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.goods_id
     *
     * @param goodsId the value for trade..trade_order.goods_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.goods_num
     *
     * @return the value of trade..trade_order.goods_num
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.goods_num
     *
     * @param goodsNum the value for trade..trade_order.goods_num
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.goods_price
     *
     * @return the value of trade..trade_order.goods_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.goods_price
     *
     * @param goodsPrice the value for trade..trade_order.goods_price
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.goods_amount
     *
     * @return the value of trade..trade_order.goods_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.goods_amount
     *
     * @param goodsAmount the value for trade..trade_order.goods_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setGoodsAmount(BigDecimal goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.shipping_fee
     *
     * @return the value of trade..trade_order.shipping_fee
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.shipping_fee
     *
     * @param shippingFee the value for trade..trade_order.shipping_fee
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.order_amount
     *
     * @return the value of trade..trade_order.order_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.order_amount
     *
     * @param orderAmount the value for trade..trade_order.order_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.coupon_id
     *
     * @return the value of trade..trade_order.coupon_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.coupon_id
     *
     * @param couponId the value for trade..trade_order.coupon_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId == null ? null : couponId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.coupon_paid
     *
     * @return the value of trade..trade_order.coupon_paid
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getCouponPaid() {
        return couponPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.coupon_paid
     *
     * @param couponPaid the value for trade..trade_order.coupon_paid
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setCouponPaid(BigDecimal couponPaid) {
        this.couponPaid = couponPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.pay_amount
     *
     * @return the value of trade..trade_order.pay_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.pay_amount
     *
     * @param payAmount the value for trade..trade_order.pay_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.money_paid
     *
     * @return the value of trade..trade_order.money_paid
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getMoneyPaid() {
        return moneyPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.money_paid
     *
     * @param moneyPaid the value for trade..trade_order.money_paid
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setMoneyPaid(BigDecimal moneyPaid) {
        this.moneyPaid = moneyPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.add_time
     *
     * @return the value of trade..trade_order.add_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.add_time
     *
     * @param addTime the value for trade..trade_order.add_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.confirm_time
     *
     * @return the value of trade..trade_order.confirm_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.confirm_time
     *
     * @param confirmTime the value for trade..trade_order.confirm_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_order.pay_time
     *
     * @return the value of trade..trade_order.pay_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_order.pay_time
     *
     * @param payTime the value for trade..trade_order.pay_time
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }
}