package zju.xyb.trade.dao.entity;

import java.math.BigDecimal;

public class TradePay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_pay.pay_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_pay.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_pay.pay_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade..trade_pay.pay_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    private Byte payStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_pay.pay_id
     *
     * @return the value of trade..trade_pay.pay_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_pay.pay_id
     *
     * @param payId the value for trade..trade_pay.pay_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_pay.order_id
     *
     * @return the value of trade..trade_pay.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_pay.order_id
     *
     * @param orderId the value for trade..trade_pay.order_id
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_pay.pay_amount
     *
     * @return the value of trade..trade_pay.pay_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_pay.pay_amount
     *
     * @param payAmount the value for trade..trade_pay.pay_amount
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade..trade_pay.pay_status
     *
     * @return the value of trade..trade_pay.pay_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade..trade_pay.pay_status
     *
     * @param payStatus the value for trade..trade_pay.pay_status
     *
     * @mbg.generated Thu Mar 21 23:40:45 CST 2019
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }
}